const { env } = process;

module.exports = {
  PORT: env.PORT || 8080,
  DB_DATABASE: env.DB_DATABASE,
  DB_USER: env.DB_USER,
  DB_PASSWORD: env.DB_PASSWORD,
  JWTKEY: env.JWTKEY,
  SENDGRID_API_KEY: env.SENDGRID_API_KEY,
  GOOGLECLIENTID: env.GOOGLECLIENTID,
  GOOGLECLIENTSECRET: env.GOOGLECLIENTSECRET,
  CLOUDINARY_CLOUD_NAME: env.CLOUDINARY_CLOUD_NAME,
  CLOUDINARY_API_KEY: env.CLOUDINARY_API_KEY,
  CLOUDINARY_API_SECRET: env.CLOUDINARY_API_SECRET,
};
